export * from './landingPages/HomePage'
export * from './landingPages/AboutPage'
export * from './landingPages/ServicePage'
export * from './landingPages/LayLeadersPage'
export * from './NotFoundPage'
export * from './landingPages/Faq'
export * from './landingPages/Gallery'
export * from './landingPages/Publication'
